<?
$PERM["referee"]["*"]="D";
$PERM["referee"]["G8"]="X";
$PERM["dashboard"]["G7"]="D";
$PERM["dashboard"]["*"]="D";
$PERM["dashboard"]["G8"]="W";
$PERM["personal"]["*"]="D";
$PERM["personal"]["G7"]="X";
$PERM["/"]["*"]="R";
$PERM["/"]["G1"]="X";
$PERM["/"]["G7"]="X";
$PERM["game-schedule"]["G7"]="R";
$PERM["index.php"]["*"]="R";
$PERM["video"]["*"]="R";
$PERM["tournaments"]["*"]="D";
$PERM["tournaments"]["7"]="X";
$PERM["matchi"]["*"]="D";
$PERM["matchi"]["7"]="X";
$PERM["pub"]["5"]="T_8";
$PERM["upload"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
?>